image: golang:1.24

stages:
  - test
  - build
  - release

variables:
  GOPATH: $CI_PROJECT_DIR/.go
  BINARY_NAME: utilities_cli

.test:
  stage: test
  script:
    - go test -v ./...
    - go install golang.org/x/lint/golint@latest
    - golint ./...
    - go fmt ./...
    - go install github.com/securego/gosec/v2/cmd/gosec@latest
    - gosec ./...
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - golangci-lint run

test:
  extends: .test

.build:
  stage: build
  script:
    - GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o $BINARY_NAME-$TARGETOS-$TARGETARCH ./cmd/cli
    - if [ "$TARGETOS" = "windows" ]; then mv $BINARY_NAME-$TARGETOS-$TARGETARCH $BINARY_NAME-$TARGETOS-$TARGETARCH.exe; fi
  artifacts:
    paths:
      - $BINARY_NAME-$TARGETOS-$TARGETARCH*
    expire_in: 1 week

build_linux_amd64:
  extends: .build
  variables:
    TARGETOS: linux
    TARGETARCH: amd64

build_linux_arm64:
  extends: .build
  variables:
    TARGETOS: linux
    TARGETARCH: arm64

build_windows_amd64:
  extends: .build
  variables:
    TARGETOS: windows
    TARGETARCH: amd64

build_macos_amd64:
  extends: .build
  variables:
    TARGETOS: darwin
    TARGETARCH: amd64

build_macos_arm64:
  extends: .build
  variables:
    TARGETOS: darwin
    TARGETARCH: arm64

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      echo "Creating release for version $CI_COMMIT_TAG"
      release-cli create --name "Release $CI_COMMIT_TAG" \
        --tag-name $CI_COMMIT_TAG \
        --description "Release $CI_COMMIT_TAG" \
        --assets-link "{\"name\":\"utilities_cli-linux-amd64\",\"url\":\"$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/utilities_cli-linux-amd64\"}" \
        --assets-link "{\"name\":\"utilities_cli-linux-arm64\",\"url\":\"$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/utilities_cli-linux-arm64\"}" \
        --assets-link "{\"name\":\"utilities_cli-windows-amd64.exe\",\"url\":\"$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/utilities_cli-windows-amd64.exe\"}" \
        --assets-link "{\"name\":\"utilities_cli-darwin-amd64\",\"url\":\"$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/utilities_cli-darwin-amd64\"}" \
        --assets-link "{\"name\":\"utilities_cli-darwin-arm64\",\"url\":\"$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/utilities_cli-darwin-arm64\"}"
  dependencies:
    - build_linux_amd64
    - build_linux_arm64
    - build_windows_amd64
    - build_macos_amd64
    - build_macos_arm64 